//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 4/21/2021 2:40:00 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace backend.Models
{
    public partial class Vehicle
    {

        public Vehicle()
        {
            this.Agents = new List<Agent>();
            OnCreated();
        }

        public string Immatricule { get; set; }

        public string Marque { get; set; }

        public DateTime DateCirculation { get; set; }

        public IList<Agent> Agents { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
