//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/21/2021 10:58:49 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace backend.Models
{
    public partial class Agent {

        public Agent()
        {
            this.Vehicles = new List<Vehicle>();
            this.Seances = new List<Seances>();
            OnCreated();
        }

        public virtual short AgentCIN { get; set; }

        public virtual string Non { get; set; }

        public virtual string Prenom { get; set; }

        public virtual DateTime DateEmb { get; set; }

        public virtual string Adresse { get; set; }

        public virtual double Salaire { get; set; }

        public virtual AgentFunction Fonction { get; set; }

        public virtual LoginAgents LoginAgents { get; set; }

        public virtual IList<Vehicle> Vehicles { get; set; }

        public virtual IList<Seances> Seances { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
