//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 4/21/2021 2:40:00 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------



namespace backend.Models
{
    public enum AgentFunction : short
    {
        Directeur = 0,
        AgentConduite = 1,
        AgentCode = 2
    }
}
