//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 4/1/2021 11:56:58 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace backend.Models
{
    public partial class Exam {

        public Exam()
        {
            OnCreated();
        }

        public virtual string Convocation { get; set; }

        public virtual string List { get; set; }

        public virtual DateTime DateExam { get; set; }

        public virtual ExamType Type { get; set; }

        public virtual Candidat Candidat { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
