//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/21/2021 10:58:49 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace backend.Models
{
    public partial class Vehicle {

        public Vehicle()
        {
            OnCreated();
        }

        public virtual string Immatricule { get; set; }

        public virtual string Marque { get; set; }

        public virtual DateTime DateCirculation { get; set; }

        public virtual Agent Agent { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
