//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/21/2021 10:58:49 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace backend.Models
{
    public partial class Seances {

        public Seances()
        {
            OnCreated();
        }

        public virtual DateTime DateSeance { get; set; }

        public virtual SeanceType SeanceType { get; set; }

        public virtual Candidat Candidat { get; set; }

        public virtual Agent Agent { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          Seances toCompare = obj as Seances;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.DateSeance, toCompare.DateSeance))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + DateSeance.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
